# Generated by Django 4.2 on 2023-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150, unique=True, verbose_name='Task name')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('In progess', 'In progess'), ('Completed', 'Completed')], default='In progess', max_length=10)),
                ('started_on', models.DateField(auto_now_add=True)),
                ('ended_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
